#!/bin/bash
set -x # echo on
# cd /xilinxworks/ZCU102/v2025.2/r5ctrlr/r5ctrlr/hardware/r5ctrlr
# sdtgen -xsa design_1_wrapper.xsa -dir output_sdt -board_dts zcu102-rev1.0
#
# petalinux-config --get-hw-description=./hardware/r5ctrlr/output_sdt/
# petalinux-config -c kernel
# petalinux-config -c rootfs
# petalinux-build -x mrproper
# petalinux-build
# petalinux-package --boot --fpga design_1_wrapper.bit --u-boot --format BIN --force --add ./R5app.elf --cpu=r5-0 --bootgen-extra-args "-log debug"
# petalinux-package --boot --fpga design_1_wrapper.bit --u-boot --format BIN --force --add ./R5app.elf --cpu=r5-0
petalinux-package boot --fpga design_1_wrapper.bit --u-boot --format BIN --force --add ./R5app.elf --cpu=r5-0
sudo rm -rf /media/valbas/boot/*
cp images/linux/{BOOT.BIN,image.ub,boot.scr} /media/valbas/boot/
sudo rm -rf /media/valbas/root/*
sudo tar xvf images/linux/rootfs.tar.gz -C /media/valbas/root
# html server stuff
# busybox-httpd stuff:
# sudo cp -r ./hardware/gitcode/r5ctrlr/linux_web_interface/srv/* /media/valbas/root/srv/.
# sudo chmod -R a+rx /media/valbas/root/srv/*
# apache stuff
sudo rm /media/valbas/root/usr/share/apache2/default-site/htdocs/index.html
sudo cp -r ./hardware/gitcode/r5ctrlr/linux_web_interface/* /media/valbas/root/.
sudo chmod -R a+rx /media/valbas/root/usr/libexec/apache2/modules/cgi-bin/*.cgi
sudo chmod -R a+rx /media/valbas/root/usr/share/apache2/default-site/htdocs/*

#
sudo cp -r ./99-petalinux /media/valbas/root/etc/sudoers.d/.
sudo chmod a+rx /media/valbas/root/etc/sudoers.d/99-petalinux
# avoid systemd warning on SysV init script
sudo rm /media/valbas/root/etc/init.d/r5ctrlr-scpi-serv-init
sudo cp ./A53app.elf /media/valbas/root/home/maxiv/.
sudo chmod a+rwx /media/valbas/root/home/maxiv/A53app.elf
# SCPI server config file (if any)
sudo cp ./scpi.conf /media/valbas/root/etc/.
sudo chmod a+rwx /media/valbas/root/etc/scpi.conf
sync
sync
sync
