#
# "maxiv distribution" configuration
# it's basically a customization of amd-edf
# which cannot be achieved in local.conf, as the distro conf overrides local.conf
# so here we are
#

require conf/distro/amd-edf.conf

# DISTRO is reset by amd-edf.conf, so we need to put it back
DISTRO = "maxiv"
DISTRO_NAME = "maxiv yocto - based on xilinx amd-edf"
DISTRO_VERSION = "v2025.2"
# also DISTROOVERRIDES was set by amd-edf.conf, so we need to put it back
# note that I enable also all xilinx "amd-edf" overrides, so I get all their standard machinery,
# but the "maxiv" distro lets me override what I want
DISTROOVERRIDES = "poky:poky-altcfg:amd-edf:maxiv"


# hostname is not set here, so it can be set in local.conf
# note that he override used in deployment is:
# hostname:pn-base-files:maxiv
#hostname:pn-base-files = "kalleanka"
#hostname:pn-base-files:amd-edf = "farbrorjoakim"
#hostname:pn-base-files:maxiv = "knaseanka"

